### PR TITLE
Feat/extensions

### PR DESCRIPTION
**Pull request by epicbrownie**
- Added AsResponse/AsResponse<T>/AsResponseAsync/AsResponseAsync<T> static Error functions
- Added AsResponse/AsResponse<T>/AsResponseAsync/AsResponseAsync<T> Error extension methods
- Added HasAttribute/RequestHasAttribute Type extensions to make conditional decorator registration easier
- Moved conditional ValidationHandler decoration to the DI config rather than in the handler
- Removed redundant SaveChangesAsync call in TransactionHandler
- Added Unit Tests to cover additions

### CODE REVIEW

**Comment by bcornett** [comment]
@epicbrownie - should we remove the error extensions from the request object? What about adding a `Request.Success()`?

**Comment by epicbrownie** [comment]
Are you proposing that we add a concrete `Request` class just for a static `Success()` method?  Or did you mean a `Response.Success()`?

I didn't remove the request `HasError` extensions since that was a (potentially) big breaking change.

I like the idea of removing the `request.Success()...` and `request.HasError()...` extensions and just using statics on `Error` and `Response` (while retaining the `<TResult>.AsResponse()...` extensions).  Whatever we decide, I'll do it Friday and update.

**Comment by bcornett** [comment]
Good call. `Response.Success()` is better.

It's a big breaking change for our 2 projects only at this point I think. We can either not upgrade to the latest yet, or modify the little code we have that's using it. I don't really like the idea of having 2 ambiguous ways of doing errors, unless we want to go the `[Obsolete]` route.

**Comment by epicbrownie** [comment]
We're on the same page.  I'll add `Response.Success()` and remove the extensions from requests on Friday.

**Pull request merged**
